# Generated by Django 5.0.7 on 2024-11-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "especialidade",
                    models.CharField(
                        choices=[
                            ("nutricionista_geral", "Nutricionista Geral"),
                            ("nutricionista_infantil", "Nutricionista Infantil"),
                            ("introducao_alimentar", "Introdução Alimentar"),
                            ("fisioterapia_geral", "Fisioterapia Geral"),
                            ("fisioterapia_infantil", "Fisioterapia Infantil"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("feminino", "Feminino"),
                            ("masculino", "Masculino"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="NutricionistaInfantil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("observacao", models.TextField(blank=True)),
                ("data_agendamento", models.DateTimeField(auto_now_add=True)),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutricionistaGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("observacao", models.TextField(blank=True)),
                ("data_agendamento", models.DateTimeField(auto_now_add=True)),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntroducaoAlimentar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("observacao", models.TextField(blank=True)),
                ("data_agendamento", models.DateTimeField(auto_now_add=True)),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FisioterapiaInfantil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("observacao", models.TextField(blank=True)),
                ("data_agendamento", models.DateTimeField(auto_now_add=True)),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FisioterapiaGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_paciente", models.CharField(max_length=255)),
                ("observacao", models.TextField(blank=True)),
                ("data_agendamento", models.DateTimeField(auto_now_add=True)),
                ("data_consulta", models.DateField()),
                ("hora_desejada", models.TimeField()),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
            ],
        ),
    ]
